### ISSUE TITLE
How long is the training process? 

### ISSUE THREAD

**Issue by ccyang123** [harvardnlp/annotated-transformer#101]
I executed the annotated-transformer code from collab. 
When I run the training step, it shows the following message for more than 5 hours:  "" Train worker process using GPU: 0 for training "" 
I didn't see any other message.  

(1) How long will I need to wait for the training process? 
(2) Instead of training by my self,  where can I get the pretrained model? 

Thanks.
Regards,

**Comment by ccyang123** [comment]
The default pretained model is "multi30k_model_final.pt", does anyone have this pretrained model? Thank you!

**Comment by ccyang123** [comment]
After I enabled the GPU in colab, the training can work properly!

**Comment by g-i-o-r-g-i-o** [comment]
> The default pretained model is "multi30k_model_final.pt", does anyone have this pretrained model? Thank you!

Did you find any pretrained model to download? Strange that it isn't available here...
