### ISSUE TITLE
Incorrect implementaion of SublayerConnection class

### ISSUE THREAD

**Issue by Milad137** [harvardnlp/annotated-transformer#110]
The current implementation of `SublayerConnection` class does not match with transformer architecture paper.
It passes $X$ to `LayerNorm` first and then passes the result to sublayer. It should be the other way around.

$\color{red}{Incorrect}$
```Python
class SublayerConnection(nn.Module):
    """
    A residual connection followed by a layer norm.
    Note for code simplicity the norm is first as opposed to last.
    """

    def __init__(self, size, dropout):
        super(SublayerConnection, self).__init__()
        self.norm = LayerNorm(size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, sublayer):
        "Apply residual connection to any sublayer with the same size."
        return x + self.dropout(sublayer(self.norm(x)))
```

$\color{green}{Correct}$
```Python
class SublayerConnection(nn.Module):
    """
    A residual connection followed by a layer norm.
    Note for code simplicity the norm is first as opposed to last.
    """

    def __init__(self, size, dropout):
        super(SublayerConnection, self).__init__()
        self.norm = LayerNorm(size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, sublayer):
        "Apply residual connection to any sublayer with the same size."
        return x + self.dropout(self.norm(sublayer(x)))
```

**Comment by StellaAthena** [comment]
Thank you for pointing this out (and good job noticing!).

While the _Attention is All You Need_ paper says it does things in the order you describe, the actual code is in the order we use here. This order (now known as "pre-layer norm") is near universally considered to be the correct way to build transformers and is used by (among others) GPT-3, PaLM, LLaMA, OPT, GPT-NeoX, and BLOOM.

**Comment by Milad137** [comment]
@StellaAthena Thank you for taking the time to clarify this.

**Comment by wayc04** [comment]
@Milad137  Hello, the approach used in the transformer may weaken stability to some extent. You can find the corresponding analysis in this paper: https://papers.cool/arxiv/2002.04745.

**Comment by wayc04** [comment]
@Milad137 Hello, the approach used in the transformer may weaken stability to some extent. You can find the corresponding analysis in this paper: https://arxiv.org/abs/2002.04745
