### ISSUE TITLE
Batch size and iterator

### ISSUE THREAD

**Issue by richielo** [harvardnlp/annotated-transformer#15]
Hello,

Thanks for the awesome work. I am trying to adapt this to my own dataset but having trouble in understanding the batch size used and the iterator as I am new to torchtext. The batch size is set as 12000 in the example but when I try to print the tensor sizes within the batch, the shapes don't really reflect that. Am I misunderstanding something? 

```
   BATCH_SIZE = 12000
    train_iter = MyIterator(train, batch_size=BATCH_SIZE, device=0,
                            repeat=False, sort_key=lambda x: (len(x.src), len(x.trg)),
                            batch_size_fn=batch_size_fn, train=True)
    i = 0
    for b in train_iter:
        i+=1
    print("steps: " + str(i))
    for b in train_iter:
        print(b.src.size())
        print(b.trg.size())
        return

"""
output
steps: 402
torch.Size([31, 203])
torch.Size([59, 203])
"""
```

Sorry for my ignorance. But how should I interpret this? Does the step equal to total data size / batch size?

Thank you very much for your help

**Comment by DaoD** [comment]
@richielo Hi there, I find the similar phenomenon.
I guess it is because the code uses dynamic batch size.
You can find batch_size_fn in MyIterator. This can dynamically builds a batch according to the data length.

**Comment by richielo** [comment]
Thanks for the reply. I think I understand that now. Do you face the problem of multigpu training in the following issue? #16 I can't seem to make it work for multigpu

**Comment by DaoD** [comment]
@richielo sorry I don't have any ideas on that problem. I'm trying to run it on a single-gpu. And deal with some OOM problems.

**Comment by Haruo195** [comment]
> @richielo sorry I don't have any ideas on that problem. I'm trying to run it on a single-gpu. And deal with some OOM problems.

@DaoD Hi, how do we change the **MultiGPULossCompute** class so that it works in a single GPU?

**Comment by yuvaraj91** [comment]
@Haruo195 did you ever find out the solution for single GPU?
