### ISSUE TITLE
errors in class MultiHeadedAttention?

### ISSUE THREAD

**Issue by Life-0-1** [harvardnlp/annotated-transformer#17]
I think this line in the MultiHeadedAttention: `l(x).view(nbatches, -1, self.h, self.d_k)` should be `l(x).view(nbatches, self.h, -1, self.d_k)`, such that the unsqueezed mask could be applied to all heads.

**Comment by AwsomeName** [comment]
[l(x).view(nbatches, -1, self.h, self.d_k).transpose(1, 2)
             for l, x in zip(self.linears, (query, key, value))]
the same line, this func apply 3 linears , return result [ l1(query), l2(key), l3(value) ]. i think this may not the idea of the multi-head attention. do i wrong??, please tell me if im wrong, thank you !

**Comment by LeoCQ707** [comment]
> 
> 
> [l(x).view(nbatches, -1, self.h, self.d_k).transpose(1, 2)
> for l, x in zip(self.linears, (query, key, value))]
> the same line, this func apply 3 linears , return result [ l1(query), l2(key), l3(value) ]. i think this may not the idea of the multi-head attention. do i wrong??, please tell me if im wrong, thank you !

Note that the multi-head attention has been considered when self.linears is defined, since its dimentsion is (d_model, d_model) rather than (d_model, d_k).
