### ISSUE TITLE
error in Batch class

### ISSUE THREAD

**Issue by huangnengCSU** [harvardnlp/annotated-transformer#19]
1.  in the function "make_tgt_mask()" of class Batch, the codes "tgt_mask = (tgt==pad),unsqueeze(-2)" maybe wrong, it should be "tgt_mask = (tgt!=pad),unsqueeze(-2)" instead.
2.  codes in future_mask "return torch.from_numpy(future_mask.astype('uint8'))" should be "return torch.from_numpy(future_mask.astype('uint8'))==0"

**Comment by mathematicsofpaul** [comment]
@huangnengCSU did you end up verifying this to be true?
