### ISSUE TITLE
Why compute the positional encodings in way of exp(log...) ?

### ISSUE THREAD

**Issue by gitfourteen** [harvardnlp/annotated-transformer#20]
Why not simply with the original expression of the paper? 
I know the expression in the code as below is equivalent to the original one:
        div_term = torch.exp(torch.arange(0, d_model, 2) *-(math.log(10000.0) / d_model))

**Comment by gitfourteen** [comment]
I guess you just refer to the alternative but math equivalent expression in [tensor2tensor](https://github.com/tensorflow/tensor2tensor/blob/23bd23b9830059fbc349381b70d9429b5c40a139/tensor2tensor/layers/common_attention.py#L424). But still I can not figure out why use **exp(log...)**. Compute faster or more stable like the way calculating log_softmax?

I am also aware of that while tensor2tensor concatenate sin and cos, here interject with each other. Are there something tricky?

**Comment by Yang-Charles** [comment]
Code reality when the formula in the original paper is deformed to avoid the risk of numerical overflow。
