### ISSUE TITLE
question in subsequent_mask

### ISSUE THREAD

**Issue by wuchen95** [harvardnlp/annotated-transformer#27]
Why use 
                        subsequent_mask = np.triu(np.ones(attn_shape), k=1).astype('uint8')
                        return torch.from_numpy(subsequent_mask) == 0

I think 
          return torch.from_numpy(np.tril(np.ones(attn_shape), k=0).astype('uint8'))
maybe is a more clear writing style for a new learner?

**Comment by SCNUJackyChen** [comment]
Maybe it just looks more tricky and more pythonic, haha.
