### ISSUE TITLE
Not Working on pytorch 1.0.1.post2

### ISSUE THREAD

**Issue by AmoghM** [harvardnlp/annotated-transformer#28]
I am consistently getting two errors which I have failed to resolve even after spending hours on it! 
Require some serious help here!!

1. RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index' 
```
.
.
.
<ipython-input-139-2ae4ba63671c> in encode(self, src, src_mask)
     17 
     18     def encode(self, src, src_mask):
---> 19         return self.encoder(self.src_embed(src), src_mask)
     20 
     21     def decode(self, memory, src_mask, tgt, tgt_mask):
.
.
.
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'
```
2. NotImplementedError
```
.
.
.
74     def encode(self, src, src_mask):
---> 75         return self.encoder(self.src_embed(src), src_mask)

```
Both has self.encoder() as fault. I can't really figure out what is happening. It will super great if someone can provide insights on this. Link to that jupyter notebook:
https://github.com/AmoghM/DeepLearning/blob/master/TransformerNetwork/HarvardTransformer.ipynb

**Comment by wesg52** [comment]
Without seeing the rest of your code my guess is that your data isn't loaded onto your GPU, but your model is

**Comment by AmoghM** [comment]
Thanks for the response. @wesg52 . I just tried with pytorch0.3.0 version as well. Same issue!
My code is available here:
https://github.com/AmoghM/DeepLearning/blob/master/TransformerNetwork/HarvardTransformer.ipynb

**Comment by ghost** [comment]
Simply change the `device` parameter to `'cuda'`:

```
train_iter = MyIterator(train, batch_size=BATCH_SIZE, device='cuda',
                        repeat=False, sort_key=lambda x: (len(x.src), len(x.trg)),
                        batch_size_fn=batch_size_fn, train=True)
valid_iter = MyIterator(val, batch_size=BATCH_SIZE, device='cuda',
                        repeat=False, sort_key=lambda x: (len(x.src), len(x.trg)),
                        batch_size_fn=batch_size_fn, train=False)
```
