### ISSUE TITLE
Is original input x copied self.h times ? (number of heads)

### ISSUE THREAD

**Issue by BerenLuthien** [harvardnlp/annotated-transformer#31]
In
```
class EncoderLayer(nn.Module):
    def forward(self, x, mask):
        x = self.sublayer[0](x, lambda x: self.self_attn(x, x, x, mask))

```
**x** is repeated 3 times for getting **k,q,v**

In

```
class MultiHeadedAttention(nn.Module):
    def __init__(self, h, d_model, dropout=0.1):
        self.d_k = d_model // h
     ...   
    def forward(self, query, key, value, mask=None):
        # 1) Do all the linear projections in batch from d_model => h x d_k 
        query, key, value = \
            [l(x).view(nbatches, -1, self.h, self.d_k).transpose(1, 2)
             for l, x in zip(self.linears, (query, key, value))]
```

there is `l(x).view(nbatches, -1, self.h, self.d_k)` 
which reshape data into `self.h` **heads**. 
This indicates the input should already have a dimension of number of heads.

Question/Confusion: I did not find where original input x is copied **self.h** times.

**Comment by lrscy** [comment]
According to my understanding, they concatenate all n headers together into single tensor, so that it's easy for Pytorch to calculate them simultaneously. All copies are initialized together and calculated separately.
