### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by ICDI0906** [harvardnlp/annotated-transformer#35]
when I run this code, there occurred some problems
(1)  in LabelSmoothing class
       this line => true_dist.index_fill_(0, mask.squeeze(), 0.0) 
       RuntimeError: invalid argument 3: Index is supposed to be a vector at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/generic/THTensorMath.cpp:569
(2) in SimpleLossCompute class
     this lien = > loss = self.criterion(x.contiguous().view(-1, x.size(-1)), y.contiguous().view(-1)) / norm
     RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'
     my torch version is 0.4.1
     does anyone have these problem? thanks~

**Comment by cuihx13** [comment]
Hello! I met the same problem in LabelSmoothing class as you proposed. Did you solve this problem? Looking forward to your reply. Thanks!

**Comment by ICDI0906** [comment]
I can't remember that, but this link https://github.com/pytorch/pytorch/issues/3416 maybe help.

**Comment by cuihx13** [comment]
Thank you very much

**Comment by nan1104** [comment]
hello, I have the same problem  in SimpleLossCompute class  as you proposed, and  can't  figure it out. Did you solve this problem? Looking forward to your reply. Thanks!
