### ISSUE TITLE
decoding loop

### ISSUE THREAD

**Issue by comja** [harvardnlp/annotated-transformer#4]
I have a question regarding the decoding loop (cell 45)

`for i, batch in enumerate(valid_iter):
`

I want to run for several validation instances not for only one. Even when I deleted `break` from the end of the loop It still fails after the first instance with error message 

`DeprecationWarning: generator 'Iterator.__iter__' raised StopIteration
`

When I replace `valid_iter` with `train_iter`. It runs for the first 42 instances then fails with the same error message.

I appreciate your help.

**Comment by srush** [comment]
I don't think that is an error, but a warning.
