### ISSUE TITLE
A mistake in attention-visualization?

### ISSUE THREAD

**Issue by OriKatz** [harvardnlp/annotated-transformer#54]
I'm looking at the section "Attention Visualization"  in the jupyter notebook: "The Annotated Transformer.ipynb".
Is there any chance that there is a mistake in the visualization code? 

When presenting the "Decoder Src Layer", the code that extracts the attention scores from the "self_attn" layers is:

`fig, axs = plt.subplots(1,4, figsize=(20, 10))
    for h in range(4):
        draw(model.decoder.layers[layer].self_attn.attn[0, h].data[:len(tgt_sent), :len(sent)], 
            sent, tgt_sent if h ==0 else [], ax=axs[h])`

Shouldn't it be replaced by the "src_attn" layer instead of the "self_attn" layer?

Thanks,
Ori

![image](https://user-images.githubusercontent.com/30949862/87230362-4ce9a200-c3b8-11ea-90b9-4e16e0e8bf17.png)

**Comment by GitMatze** [comment]
You're right! I've been wondering why in these figures the decoder source layers are masked (they shoudn't, right?). Now I understand. Thanks for pointing that out!
