### ISSUE TITLE
Torch Version -- cannot import from torchtext

### ISSUE THREAD

**Issue by bgonggw** [harvardnlp/annotated-transformer#59]
Hello, I keep running into problems when importing from torchtext. If I do "from torchtext import data, datasets" it will either throw error no attribute "float32" or no "dtype_attr"--tried changing the versions of pytorch to latest or torchtext but without avail. Any ideas would be appreciated!

/usr/local/lib/python3.6/dist-packages/torchtext/data/field.py in Field()
    122     # numeric type.
    123     dtypes = {
--> 124         torch.float32: float,
    125         torch.float: float,
    126         torch.float64: float,

AttributeError: module 'torch' has no attribute 'float32'

**Comment by bobbyhaliwela** [comment]
Try installing this version
`!pip install torchtext==0.2.3`
