### ISSUE TITLE
A question in class Embeddings(nn.Module)

### ISSUE THREAD

**Issue by nxznm** [harvardnlp/annotated-transformer#60]
Hello, sorry to bother you!
I notice that in forward function, you `return self.lut(x) * math.sqrt(self.d_model)` rather than `return self.lut(x)`, I want to know the reason (is this a trick?), because I find that the test result will be bad if I don't multiply `math.sqrt(self.d_model)`.
```
class Embeddings(nn.Module):
    def __init__(self, d_model, vocab):
        super(Embeddings, self).__init__()
        self.lut = nn.Embedding(vocab, d_model)
        self.d_model = d_model

    def forward(self, x):
        return self.lut(x) * math.sqrt(self.d_model)
```

**Comment by IamAdiSri** [comment]
I also have a question about the embeddings. The paper says, _"...we **share the same weight matrix** between the two embedding layers..."_ In the code however, the encoder and decoder have their own independent embedding matrices.

Why is there this inconsistency?

**Comment by wangjunhe8127** [comment]
> 我还有一个关于嵌入的问题。论文称，_“……我们在两个嵌入层之间**共享相同的权重矩阵**_……”然而，在代码中，编码器和解码器拥有自己独立的嵌入矩阵。
> 
> 为什么会出现这种不一致的情况呢？



> I also have a question about the embeddings. The paper says, _"...we **share the same weight matrix** between the two embedding layers..."_ In the code however, the encoder and decoder have their own independent embedding matrices.
> 
> Why is there this inconsistency?

i have the same question

**Comment by khty2000** [comment]
> > 我还有一个关于嵌入的问题。论文称，_“……我们在两个嵌入层之间**共享相同的权重矩阵**_……”然而，在代码中，编码器和解码器拥有自己独立的嵌入矩阵。
> > 为什么会出现这种不一致的情况呢？
> 
> > I also have a question about the embeddings. The paper says, _"...we **share the same weight matrix** between the two embedding layers..."_ In the code however, the encoder and decoder have their own independent embedding matrices.
> > Why is there this inconsistency?
> 
> i have the same question

src_vocab and tgt_vocab have different values, so the matirxs of lux dont have same dims. i dont think they can be same in this example.  maybe only in this case[When using BPE with shared vocabulary we can share the same weight vectors between the source / target / generator]，they can be same
