### ISSUE TITLE
Any Plan on Adding Beam Search?

### ISSUE THREAD

**Issue by ustctf-zz** [harvardnlp/annotated-transformer#8]
Thanks for providing this fine-grained tutorial on reproducing Transformer in Pytorch!

I'm wondering if you have any plan on adding the support for beam search? Thanks!

Best

**Comment by srush** [comment]
Yes. I will add a minimal reference beam search implementation. It might be a separate notebook though.

**Comment by ustctf-zz** [comment]
Thanks @srush ! Looking forward to this implementation.
