### ISSUE TITLE
Use of `deepcopy` in `clones` function

### ISSUE THREAD

**Issue by PierreAndreNoel** [harvardnlp/annotated-transformer#9]
The code duplicate encoder/decoder layers using the following `clones` function:
```
def clones(module, N):
    "Produce N identical layers."
    return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])
```

My understanding is that this would cause all layers to share the same random initial values for the learnable parameters, which is likely non-optimal. Is this just to make the code simpler? I feel like there are easy alternatives, e.g.:
```
def clones(module_fn, N):
    "Produce N identical layers."
    return nn.ModuleList([module_fn() for _ in range(N)])
```

On a different notes, kudos for writing such a clear and useful document!

**Comment by PierreAndreNoel** [comment]
Nvm, I just saw the `nn.init.xavier_uniform(p)`.

**Comment by tshrjn** [comment]
Hi @PierreAndreNoel, could you please elaborate on why deep copy helps? Since the weight init is from uniform, returning `nn.ModuleList([module_fn() for _ in range(N)])` looks to me it would return the same exact thing.

**Comment by PierreAndreNoel** [comment]
@tshrjn

>  could you please elaborate on why deep copy helps?

I think that there is a misunderstanding: I don't think it helps, but its fine here because of the later call to `nn.init.xavier_uniform(p)`.

My first piece of code is directly quoted from `In [5]` of https://github.com/harvardnlp/annotated-transformer/blob/master/The%20Annotated%20Transformer.ipynb at 9736cf2 , i.e., harvardnlp/@srush 's code. My original comment was that this could be problematic, and I proposed the fix in the second piece of code. I personally would prefer the second piece of code.
