### ISSUE TITLE
Should the model LayerNorm before encoding?

### ISSUE THREAD

**Issue by dawei-yu** [harvardnlp/annotated-transformer#92]
Hello, It seems your code LayerNorm inputs before encoding.
x->EncoderDecoder(x)->Encoder(x)->EncoderLayer(x)->SublayerConnection(x): x + self.dropout(sublayer(self.norm(x))).
But in the attention is all you need, the model don't LayerNorm before encoding.

**Comment by StellaAthena** [comment]
… that’s sorta correct. Firstly, it’s important to note that what we do (called “pre-layer norm”) is now widely accepted as superior to what the paper described (called “post-layer norm”)

Noam Shazeer figured out that they did layer normalization wrong __only a couple weeks__ after *Attention is All You Need* came out. He updated the codebase to do it correctly, but never changed the paper. You can find the commit he introduced the change into TensorFlow with here: https://github.com/tensorflow/tensor2tensor/commit/f5c9b17e617ea9179b7d84d36b1e8162cb369f25

The paper I credit with correcting the layer normalization used in transformers, *On Layer Normalization in the Transformer Architecture*, came out in 2020. Somehow the knowledge that this method is superior never percolated in the community until this paper.

So yes, our code is different from the Attention is All You Need paper. However it follows what is today considered best practices and is not different from the code associated with that paper.

**Comment by dawei-yu** [comment]
> … that’s sorta correct. Firstly, it’s important to note that what we do (called “pre-layer norm”) is now widely accepted as superior to what the paper described (called “post-layer norm”)
> 
> Noam Shazeer figured out that they did layer normalization wrong **only a couple weeks** after _Attention is All You Need_ came out. He updated the codebase to do it correctly, but never changed the paper. You can find the commit he introduced the change into TensorFlow with here: [tensorflow/tensor2tensor@f5c9b17](https://github.com/tensorflow/tensor2tensor/commit/f5c9b17e617ea9179b7d84d36b1e8162cb369f25)
> 
> The paper I credit with correcting the layer normalization used in transformers, _On Layer Normalization in the Transformer Architecture_, came out in 2020. Somehow the knowledge that this method is superior never percolated in the community until this paper.
> 
> So yes, our code is different from the Attention is All You Need paper. However it follows what is today considered best practices and is not different from the code associated with that paper.

Wow, a detail and professional reply, thanks

**Comment by aambrioso1** [comment]
Thank you for that amazing insight!

**Comment by StrongerXi** [comment]
Interestingly, the Megatron-LM and T5 papers also ended up using pre-layernorm, although they came out during 2019. Yet for some reason [BERT](https://github.com/google-research/bert/blob/eedf5716ce1268e56f0a50264a88cafad334ac61/modeling.py#L862-L880) (2018) didn't end up doing that.
